server:
  port: 8030

spring:
  datasource:
    username: root
    password: root
    #url: jdbc:mysql://119.29.193.73:3306/lem-inter?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/lem-inter?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 119.29.193.73
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 200  #连接池最大允许连接数
        max-wait: 600000  #连接池最大阻塞等待时间
        max-idle: 20     #连接池中最大的连接空闲数
        min-idle: 0      #连接池中最小的连接空闲数
        timeout: 600000   #连接超时时间
    database: 0
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: fmnykoeamnhqieej
    username: 1530916212@qq.com
    port: 587
    properties:
      mail:
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug